services:
 mysql:
  image: mysql:8.0
  container_name: mysql-spring
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 1234
   MYSQL_DATABASE: BD_STREAMHUB
  ports:
   - "3307:3306"
  volumes:
   - mysql_data:/var/lib/mysql
 app:
  build: .
  container_name: spring-app
  restart: always
  depends_on:
   - mysql
  ports:
  - "8081:8081"
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BD_STREAMHUB
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: 1234
volumes:
 mysql_data: